testtask/testtask/urls.py
from django.contrib import admin
from django.urls import path, re_path
from bookstore import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls , ),
    re_path(r'^main$', views.BookList.as_view(), name="bookstore-main"),
    re_path(r'^book/(?P<pk>[0-9]+)$', views.BookDetails.as_view(extra_context={'title': 'Book Info'}), name='bookstore-bookinfo'),
    re_path(r'^book/add$', views.AddBook.as_view(extra_context={'title': 'Create new book'}), name='bookstore-addBook'),
    re_path(r'^book/(?P<pk>[0-9]+)/edit$', views.EditBook.as_view(extra_context={'title': 'Edit book information'}), name='bookstore-editBook'),
    re_path(r'^author/(?P<pk>[0-9]+)$', views.AuthorDetails.as_view(extra_context={'title': 'Author Info'}), name='bookstore-authorinfo'),
    re_path(r'^author/add$', views.AddAuthor.as_view(extra_context={'title': 'Create new author'}), name='bookstore-addAuthor'),
    re_path(r'^author/(?P<pk>[0-9]+)/edit$', views.EditAuthor.as_view(extra_context={'title': 'Edit author information'}), name='bookstore-editAuthor'),
    re_path(r'^accounts/login/$', auth_views.login,  {'template_name': 'login.html'}, name='login'),
    re_path(r'^accounts/logout/$', auth_views.logout, {'next_page': '/accounts/login'}, name='logout'),
    re_path(r'^requests/$', views.RequestInfo.as_view(extra_context={'title': 'Requests'}), name='request'),
]

testtask/bookstore/models.py
from django.db import models
import datetime
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('Author',on_delete=models.CASCADE)
    ISBN = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    publish_date = models.DateField(default=datetime.datetime.today().strftime('%Y-%m-%d'))

    def __str__(self):
        return "{}".format(self.title)

    def get_absolute_url(self):
        return reverse('bookstore-bookinfo', kwargs={'pk': self.pk})


class Author(models.Model):
    name = models.CharField(max_length=25)
    surname = models.CharField(max_length=25)

    def __str__(self):
        return "{}.{}".format(self.name[0],self.surname)

    def get_absolute_url(self):
        return reverse('bookstore-authorinfo', kwargs={'pk': self.pk})


class Requests(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    path = models.CharField(max_length=1000)
    method = models.CharField(max_length=50)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    post = models.TextField(blank=True, null=True)

testtask/bookstore/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView
from django import forms
from django.urls import reverse_lazy
from bookstore.models import Book,Author,Requests
from django.contrib.auth.decorators import *
from django.utils.decorators import method_decorator


# Create your views here.
class BookList(ListView):
    model = Book
    template_name = 'bookList.html'
    title = 'Main Page'

    def get(self, request, *args, **kwargs):
        queryset = Book.objects.all().order_by('-publish_date')
        self.request.session['ordered'] = 'asc'
        return render(request,self.template_name,{'object_list':queryset,'title':self.title})

    def post(self,request):
        queryset = Book.objects.all()
        if self.request.session['ordered'] == 'asc':
            self.request.session['ordered'] = 'desc'
            queryset = queryset.order_by('publish_date')
        else:
            self.request.session['ordered'] = 'asc'
            queryset = queryset.order_by('-publish_date')
        return render(request, self.template_name, {'object_list': queryset, 'title':self.title})

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class BookDetails(DetailView):
    model = Book
    template_name = 'bookInfo.html'
    context_object_name = 'book'


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'ISBN', 'price', 'publish_date']
        widgets = {
            'title' : forms.TextInput(attrs={'size' : '40',  'class':'form-control'}),
            'author': forms.Select(attrs={'class':'form-control'}),
            'price':forms.TextInput(attrs={"type":"number",'class':'form-control'}),
            'ISBN': forms.TextInput(attrs={'size' : '40', 'class':'form-control'}),
            'publish_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }


class AddBook(CreateView):
    model = Book
    template_name = 'bookCreate.html'
    success_url = reverse_lazy('bookstore-main')
    form_class = BookForm

    @method_decorator(login_required)
    @method_decorator(permission_required('bookstore.change_book', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class EditBook(UpdateView):
    model = Book
    template_name = 'bookUpdate.html'
    form_class = BookForm

    @method_decorator(login_required)
    @method_decorator(permission_required('bookstore.change_book', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('bookstore-bookinfo', kwargs={'pk': self.kwargs['pk']})


class AuthorDetails(DetailView):
    model = Author
    template_name = 'authorInfo.html'
    context_object_name = 'author'


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'surname']
        widgets = {
             'name': forms.TextInput(attrs={'size' : '40',  'class':'form-control'}),
             'surname': forms.TextInput(attrs={'size' : '40',  'class':'form-control'}),
        }


class AddAuthor(CreateView):
    model = Author
    template_name = 'authorCreate.html'
    success_url = reverse_lazy('bookstore-main')
    form_class = AuthorForm

    @method_decorator(login_required)
    @method_decorator(permission_required('bookstore.add_author', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class EditAuthor(UpdateView):
    model = Author
    template_name = 'authorUpdate.html'
    form_class = AuthorForm

    @method_decorator(login_required)
    @method_decorator(permission_required('bookstore.add_author', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('bookstore-authorinfo', kwargs={'pk': self.kwargs['pk']})


class RequestInfo(ListView):
    model = Requests
    template_name = 'requestList.html'
    title = 'Request Page'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['list'] = Requests.objects.all().order_by('-time')[:10]
        except:
            context['list'] = Requests.objects.all().order_by('-time')
        return context

    @method_decorator(login_required)
    @method_decorator(permission_required('is_superuser', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

testtask/bookstore/templates/authorCreate.html
{% extends "base.html" %}
{% block CreateBlock %}
        <h2 style="text-align:center">Add a new author</h2>
        <div style="position: relative; width:20%; left: 40%"">
        <form method="post" id="createForm" >
            {% csrf_token %}
            <div class="form-group">
                        {{ form.name.errors }}
                        <label for="id_title">Name:</label>
                        {{ form.name }}
                </div>
                <div class="form-group">
                            {{ form.surname.errors }}
                        <label for="id_author">Surname:</label>
                        {{ form.surname }}
                </div>
            <button type="submit" style="margin-left: 40%" class="btn btn-primary" form="createForm">Create</button>
        </form>
        </div>
        <script>
            $("div > label").css("margin-left","40%");
        </script>
{% endblock %}

testtask/bookstore/templates/authorInfo.html
{% extends "base.html" %}
{% block InfoBlock %}
{% load checkGroup %}
    <h2 style="text-align:center"> Author Page</h2>
    <div style="width: 30%; position: relative; left: 35%;">
    <ul class="list-group">
            <li class="list-group-item">Name: {{ author.name }}</li>
            <li class="list-group-item">Surname: {{ author.surname}}</li>
    </ul>
    </div>
    {% if request.user|has_group:"Manager" or request.user.is_superuser %}
    {% url 'bookstore-editAuthor' author.id as the_url %}
    <button style="position: relative; left:40%; width: 5%; margin-top: 10px"  class="btn btn-primary" onClick='location.href="{{the_url}}"'>Edit</button>
    {% endif %}
    {% url 'bookstore-main' as the_url %}
    <button style="position: relative; left:47%; width: 5%; margin-top: 10px"  class="btn btn-primary" onClick='location.href="{{the_url}}"'>Back</button>
{% endblock %}

testtask/bookstore/templates/authorUpdate.html
{% extends "base.html" %}
{% block UpdateBlock %}
        <h2 style="text-align:center">Add a new author</h2>
        <div style="position: relative; width:20%; left: 40%"">
        <form method="post" id="createForm" >
            {% csrf_token %}
            <div class="form-group">
                    {{ form.name.errors }}
                    <label for="id_title">Name:</label>
                    {{ form.name }}
            </div>
            <div class="form-group">
                        {{ form.surname.errors }}
                    <label for="id_author">Surname:</label>
                    {{ form.surname }}
            </div>
            <button type="submit" style="margin-left: 40%" class="btn btn-primary" form="createForm">Update</button>
        </form>
        </div>
        <script>
            $("div > label").css("margin-left","40%");
        </script>
{% endblock %}

testtask/bookstore/templates/base.html
<!DOCTYPE>
<html>
    <head>
        <title>{{title}}</title>
        {% load staticfiles %}
        {% load checkGroup %}
        <link rel="stylesheet" rel="stylesheet"  href="{% static 'bookstore/bootstrap/css/bootstrap.min.css' %}">
        <script src="{% static 'bookstore/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'bookstore/javascript/jquery-3.3.1.min.js' %}"></script>
        <link rel="stylesheet" rel="stylesheet"  href="{% static 'bookstore//css/fotter.css' %}">
    </head>
    <body>
            {% if user.is_anonymous %}
            {% url 'login' as the_url %}
            <nav class="navbar navbar-light bg-light">
            <a  href="{{the_url}}">Press to login</a>
            </nav>
            {% elif request.user|has_group:"Customer" %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link disabled" href="#">Hello Customer</a>
                            </li>
                            <li class="nav-item">
                                    {% url 'bookstore-main' as the_url %}
                                    <a class="nav-link" href="{{the_url}}"> Home</a>
                            </li>
                            <li class="nav-item">
                                    {% url 'logout' as the_url %}
                                <a class="nav-link" href="{{the_url}}">Logout</a>
                            </li>
                        </ul>
                    </div>
            </nav>
            {% elif request.user|has_group:"Manager" or request.user.is_superuser %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link disabled" href="#">Hello</a>
                            </li>
                            <li class="nav-item">
                                {% url 'bookstore-main' as the_url %}
                                <a class="nav-link" href="{{the_url}}"> Home</a>
                            </li>
                            <li class="nav-item">
                                {% url 'bookstore-addBook' as the_url %}
                                <a class="nav-link" href="{{the_url}}">Add book</a>
                            </li>
                            <li class="nav-item">
                                    {% url 'bookstore-addAuthor' as the_url %}
                                    <a class="nav-link" href="{{the_url}}">Add author</a>
                                </li>
                            <li class="nav-item">
                                 {% url 'logout' as the_url %}
                                 <a class="nav-link" href="{{the_url}}">Logout</a>
                            </li>
                        </ul>
                    </div>
            </nav>
        {% endif %}

        {% block bookList %}{% endblock %}
        {% block RequestList %}{% endblock %}
        {% block InfoBlock %}{% endblock %}
        {% block CreateBlock %}{% endblock %}
        {% block UpdateBlock %}{% endblock %}
    <footer class="footer">
        <p>	TestTask &#169; 2018—2018</p>
    </footer>
    </body>
</html>

testtask/bookstore/templates/bookCreate.html
{% extends "base.html" %}
{% block CreateBlock %}
{% for field in form %}
	{% endfor %}
        <h2 style="text-align:center">Add a new book</h2>
        <div style="position: relative; width:20%; left: 40%"">
        <form method="post" id="createForm" >
            {% csrf_token %}
            <div class="form-group">
                        {{ form.title.errors }}
                        <label for="id_title">Title:</label>
                        {{ form.title }}
                </div>
                <div class="form-group">
                       {{ form.author.errors }}
                        <label for="id_author">Author:</label>
                        {{ form.author }}
                </div>
                <div class="form-group">
                         {{ form.price.errors }}
                        <label for="id_price">Price:</label>
                        {{ form.price }}
                </div>
                <div class="form-group">
                        {{ form.ISBN.errors }}
                        <label for="id_ISBN">ISBN:</label>
                        {{ form.ISBN }}
                </div>
                <div class="form-group">
                       {{ form.publish_date.errors }}
                        <label for="id_publich_date">Publish Date:</label>
                        {{ form.publish_date }}
                </div>
            <button type="submit" style="margin-left: 40%" class="btn btn-primary" form="createForm">Create</button>
        </form>
        </div>
        <script>
            $("div > label").css("margin-left","40%");
        </script>
{% endblock %}

testtask/bookstore/templates/bookInfo.html
{% extends "base.html" %}
{% block InfoBlock %}
{% load checkGroup %}
    <h2 style="text-align:center"> The information about "{{book.title}}"</h2>
    <div style="width: 30%; position: relative; left: 35%;">
    <ul class="list-group">
            {% url 'bookstore-authorinfo' book.author.id as the_url %}
            <li class="list-group-item">Author: <a href='{{ the_url }}'>{{book.author }}</a></li>
            <li class="list-group-item">Publish date: {{ book.publish_date}}</li>
            <li class="list-group-item">Price:  {{ book.price}}</li>
            <li class="list-group-item">ISBN:  {{ book.ISBN}}</li>
    </ul>
    </div>
    {% if request.user|has_group:"Manager" or request.user.is_superuser %}
    {% url 'bookstore-editBook' book.id as the_url %}
    <button style="position: relative; left:40%; width: 5%; margin-top: 10px"  class="btn btn-primary" onClick='location.href="{{the_url}}"'>Edit</button>
    {% endif %}
    {% url 'bookstore-main' as the_url %}
    <button style="position: relative; left:47%; width: 5%; margin-top: 10px"  class="btn btn-primary" onClick='location.href="{{the_url}}"'>Back</button>
{% endblock %}

testtask/bookstore/templates/bookList.html
{% extends "base.html" %}
{% block bookList %}
        {% if request.user.is_superuser %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                         <a class="nav-link" href="http://127.0.0.1:8000/admin/bookstore/book/">Admin page</a>
                    </li>
                    {% url 'request' as the_url %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{the_url}}">Request list</a>
                   </li>
                </ul>
            </div>
    </nav>
        {% endif %}
        <h2 style="text-align:center"> Here is list of books available in the store</h2>
        <form method='post' id='order'>
                {% csrf_token %}
                <button type='submit' style="margin-left: 45%" class="btn btn-primary" form="order">Order by date</button>
        </form>
    <table class="table" style="width:50%; position:relative;left:25%">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">ISBN</th>
            <th scope="col">Price</th>
            <th scope="col">Publish date</th>
          </tr>
        </thead>
        <tbody>
            {% for book in object_list %}
            {% url 'bookstore-bookinfo' book.id as the_url %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href='{{ the_url }}'>{{book.title}}</a></td>
                {% url 'bookstore-authorinfo' book.author.id as the_url %}
                <td><a href='{{ the_url }}'>{{book.author }}</a></td>
                <td>{{book.ISBN}}</td>
                <td>{{book.price}}</td>
                <td>{{book.publish_date}}</td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
{% endblock %}

testtask/bookstore/templates/bookUpdate.html
{% extends "base.html" %}
{% block UpdateBlock %}
        <h2 style="text-align:center">Update the book</h2>
        <div style="position: relative; width:20%; left: 40%">
        <form method="post" id="editForm" >
            {% csrf_token %}
            <div class="form-group">
                    {{ form.title.errors }}
                    <label for="id_title">Title:</label>
                    {{ form.title }}
            </div>
            <div class="form-group">
                   {{ form.author.errors }}
                    <label for="id_author">Author:</label>
                    {{ form.author }}
            </div>
            <div class="form-group">
                     {{ form.price.errors }}
                    <label for="id_price">Price:</label>
                    {{ form.price }}
            </div>
            <div class="form-group">
                    {{ form.ISBN.errors }}
                    <label for="id_ISBN">ISBN:</label>
                    {{ form.ISBN }}
            </div>
            <div class="form-group">
                   {{ form.publish_date.errors }}
                    <label for="id_publich_date">Publish Date:</label>
                    {{ form.publish_date }}
            </div>
            <input type="submit" style="margin-left: 40%" class="btn btn-primary" form="editForm" value="Update">
        </form>
        </div>
        <script>
            $("div > label").css("margin-left","40%");
        </script>
{% endblock %}

testtask/bookstore/templates/login.html
<!DOCTYPE>
<html>
    <head>
        <title>Login</title>
        {% load staticfiles %}
        <link rel="stylesheet" rel="stylesheet"  href="{% static 'bookstore/bootstrap/css/bootstrap.min.css' %}">
        <script src="{% static 'bookstore/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'bookstore/javascript/jquery-3.3.1.min.js' %}"></script>
        <link rel="stylesheet" rel="stylesheet"  href="{% static 'bookstore//css/fotter.css' %}">
        <script>
            $( document ).ready(function() {
                $('#id_password').addClass('form-control');
                $('#id_username').addClass('form-control');
                $("div > label").css("margin-left","40%");
            });
        </script>
    </head>
    <body>
        <h2 style="text-align:center">Login</h2>
        <div style="position: relative; width:20%; left: 40%">
        <form method="post" id='login'>
            {% csrf_token %}
            <div class="form-group">
                    {{ form.username.errors }}
                    <label for="id_username">Title:</label>
                    {{ form.username }}
            </div>
            <div class="form-group">
                    {{ form.password.errors }}
                    <label for="id_password">Author:</label>
                    {{ form.password }}
            </div>
            <button type="submit" style="margin-left: 40%" class="btn btn-primary" form="login">Login</button>
        </form>
    </div>
    </body>
</html>

testtask/bookstore/templates/requestList.html
{% extends "base.html" %}
{% block bookList %}
        <h2 style="text-align:center"> Here is list of ten latest requests</h2>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Time</th>
            <th scope="col">Path</th>
            <th scope="col">Method</th>
            <th scope="col">User</th>
            <th scope="col">Post data</th>
          </tr>
        </thead>
        <tbody>
            {% for req in list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{req.time}}</td>
                <td>{{req.path}}</td>
                <td>{{req.method}}</td>
                <td>{{req.user}}</td>
                <td>{{req.post}}</td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
{% endblock %}